services:
  react-app:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app      # สมมุติโค้ด React อยู่โฟลเดอร์ frontend
      - /app/node_modules    # ป้องกันการแมปโฟลเดอร์ node_modules จาก host
    command:  sh -c "npm install && npm run dev -- --host"
    ports:
      - "3000:5173"          # เปิดพอร์ต 3000 (host) ไป 5173 (container, vite default)
    environment:
      - CHOKIDAR_USEPOLLING=true  # ช่วยเรื่อง hot reload บน Windows/Linux บางกรณี
      - HOST=0.0.0.0