name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: read
  security-events: write  # 🟢 จำเป็นสำหรับ upload-sarif
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image for Node.js
        run: |
          docker build -t manaphat/Project1-v1 .
      - name: Push Docker image to Docker Hub
        run: |
          docker push manaphat/Project1-v1
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
            image-ref: 'manaphat/Project1-v1'
            exit-code: '0'  # Exit if vulnerabilities of severity 'CRITICAL' or 'HIGH' are found
            ignore-unfixed: true
            vuln-type: 'os,library'
            format: 'sarif'  # เปลี่ยนจาก --template เป็น --format
            output: 'trivy-results.sarif'
            severity: 'CRITICAL,HIGH'  
        continue-on-error: true  # ไม่ให้ workflow fail แม้เจอช่องโหว่
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
