name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
permissions:
  contents: read           # อ่านโค้ดใน repo
  actions: read            # อ่านข้อมูล workflow
  security-events: write   # เขียน/อัปโหลดผล security scan
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image for Node.js
        run: |
          docker build -t manaphat/project1-v1 .
      - name: Push Docker image to Docker Hub
        run: |
          docker push manaphat/project1-v1
      - name: Run Trivy vulnerability scanner and print output
        run: |
          trivy image --exit-code 0 --ignore-unfixed --vuln-type os,library --severity CRITICAL,HIGH manaphat/project1-v1
      - name: Run Trivy vulnerability scanner (SARIF output)
        uses: aquasecurity/trivy-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.JAGITHUB_TOKEN }}
        with:
          image-ref: 'manaphat/project1-v1'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
        continue-on-error: true
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        env:
          GITHUB_TOKEN: ${{ secrets.JAGITHUB_TOKEN }}
        with:
          sarif_file: 'trivy-results.sarif'
